### ISSUE TITLE
Debian 11.6.0 install ModuleNotFoundError: No module named 'tkinter' when launching

### ISSUE THREAD

**Issue by chaospup** [joshpatten/PVE-VDIClient#49]
Traceback (most recent call last):
  File "/home/jld/PVE-VDIClient/./vdiclient.py", line 3, in <module> import PySimpleGUI as sg # pip install PySimpleGUI
  File "/home/jld/.local/lib/python3.9/site-packages/PySimpleGUI/__init__.py", line 2, in <module> from .PySimpleGUI import *
  File "/home/jld/.local/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 136, in <module> import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by joshpatten** [comment]
try running `apt install python3-tk` and see if that fixes your issue.
