### ISSUE TITLE
Got an error when connected to a desktop instance

### ISSUE THREAD

**Issue by stefen-jms** [joshpatten/PVE-VDIClient#51]
![image](https://user-images.githubusercontent.com/80803090/224245398-3451af3a-5c44-4f14-856b-e17e48983ca6.png)

Traceback (most recent call last):
  File "vdiclient.py", line 496, in <module>
  File "vdiclient.py", line 486, in main
  File "vdiclient.py", line 455, in showvms
  File "vdiclient.py", line 275, in vmaction
  File "proxmoxer\core.py", line 172, in post
  File "proxmoxer\core.py", line 149, in _request
proxmoxer.core.ResourceException: 500 Internal Server Error: no spice port

**Comment by joshpatten** [comment]
A note: the reason you got this error is because the VM isn't configured to use SPICE. I've added code to catch this and issue a popup rather than crashing.
